version: "3.1"

services:
    mariadb:
        container_name: sf5multitenancy_mariadb
        image: mariadb:10.4
        working_dir: /application
        volumes:
            - ./:/application
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sf5_multi_tenancy
        ports:
            - "8083:3306"

    webserver:
        container_name: sf5multitenancy_webserver
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ./:/application:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php-fpm:
        container_name: sf5multitenancy_phpfpm
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - ./:/application:cached
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    adminer:
        container_name: sf5multitenancy_adminer
        image: adminer
        restart: on-failure
        ports:
            - '9002:8080'